mapzen/open

pom.xml
src/main/java/com/mapzen/open/activity/BaseActivity.java
src/main/java/com/mapzen/open/core/AppModule.java
src/main/java/com/mapzen/open/core/CommonModule.java
src/main/java/com/mapzen/open/core/MapzenLocation.java
src/main/java/com/mapzen/open/login/LoginActivity.java
src/main/java/com/mapzen/open/route/RouteFragment.java
src/test/java/com/mapzen/open/activity/BaseActivityTest.java
src/test/java/com/mapzen/open/core/MapzenLocationTest.java
src/test/java/com/mapzen/open/core/TestAppModule.java
src/test/java/com/mapzen/open/fragment/ItemFragmentTest.java
src/test/java/com/mapzen/open/login/LoginActivityTest.java
src/test/java/com/mapzen/open/route/RouteFragmentTest.java
src/test/java/com/mapzen/open/support/TestBaseActivity.java

New and improved location services with LOST

---

src/main/java/com/mapzen/open/route/RouteFragment.java
src/test/java/com/mapzen/open/route/RouteFragmentTest.java

* Declares constants for panel offset values
* Inverts offset conditionals
* Ensures panel contents are visible when fully expanded

Update SlidingUpPanel offset logic

---

res/values/styles.xml

Change colorPrimary from transparent white to solid

Semi-transparent primary style color causes crashes

---

src/main/java/com/mapzen/open/activity/BaseActivity.java
src/test/java/com/mapzen/open/activity/BaseActivityTest.java

Manually set iconified to false on expand

SearchView should not be iconified when expanded

---

src/main/java/com/mapzen/open/activity/BaseActivity.java
src/main/java/com/mapzen/open/search/AutoCompleteAdapter.java
src/main/java/com/mapzen/open/search/PagerResultsFragment.java
src/main/java/com/mapzen/open/search/PeliasSearchView.java
src/test/java/com/mapzen/open/activity/BaseActivityTest.java
src/test/java/com/mapzen/open/search/AutoCompleteAdapterTest.java
src/test/java/com/mapzen/open/search/PagerResultsFragmentTest.java
src/test/java/com/mapzen/open/search/PeliasSearchViewTest.java

* Replaces native SearchView with support version
* Move show/hide of auto complete list view inside PeliasSearchView

Use v7 compatibility SearchView

---

src/main/java/com/mapzen/open/adapters/SearchViewAdapter.java
src/main/java/com/mapzen/open/core/AppModule.java
src/main/java/com/mapzen/open/entity/SimpleFeature.java
src/test/java/com/mapzen/open/adapters/SearchViewAdapterTest.java
src/test/java/com/mapzen/open/core/TestAppModule.java
src/test/java/com/mapzen/open/entity/SimpleFeatureTest.java

* Adds click listener to post RoutePreviewEvent
* Adds SearchViewAdapterTest class
* Removes SimpleFeature ViewHolder since views are not recycled by default in ViewPager.
* Injects SearchViewAdapter and SearchViewAdapterTest

Fix start route button

---

res/layout/base.xml
res/layout/fragment_search_results.xml
src/main/java/com/mapzen/open/search/PagerResultsFragment.java

* Moves pagination view to base layout
* Toggle visibility based on search results
* Sets attribution position based on view pager height only

Fix attribution padding when displaying search results

---

res/layout/direction_list_item.xml
res/layout/divider.xml
res/layout/full_results_list.xml
res/layout/search_dropdown_item.xml
res/layout/search_result_list_item.xml
res/layout/search_result_pager_item.xml
res/menu/options_menu.xml
res/values/colors.xml

small style tweaks and icon replacements

---

src/main/java/com/mapzen/open/route/RoutePreviewFragment.java

Replaces `BOTTOM_CENTER` with `CENTER` for new start pin.

Update start route marker position.

---

res/layout-land/route_preview.xml

Default to car icon on rotation

---

res/layout-land/route_header.xml
res/layout/route_header.xml

Center vertical locate me icon in reverse preview mode and add padding

---

res/layout/fragment_direction_list.xml
res/values/dimens.xml

padding the list divider

---

src/main/java/com/mapzen/open/fragment/MapFragment.java
src/test/java/com/mapzen/open/fragment/MapFragmentTest.java

Intermittent crashes on rotation.

Null check map and layers before showing location marker

---

res/layout/direction_list_item.xml
res/layout/fragment_direction_list.xml

Moves left and right padding from list view to individual items

Remove scrollbar padding in direction list

---

src/main/java/com/mapzen/open/activity/BaseActivity.java
src/main/java/com/mapzen/open/core/MapzenLocation.java
src/main/java/com/mapzen/open/route/RouteFragment.java
src/main/java/com/mapzen/open/util/Logger.java
src/test/java/com/mapzen/open/shadows/ShadowMapView.java
src/test/java/org/oscim/map/TestMap.java

Avoid NPEs on configuration change while routing

Adds null checks to improve stability in routing mode

---

src/main/java/com/mapzen/open/route/RouteFragment.java
src/test/java/com/mapzen/open/route/RouteFragmentTest.java

Otherwise it might not come back!
Also re-hide base activity locate me button and attribution after rerouting.

Avoid hiding route footer when recalculating

---

src/main/java/com/mapzen/open/activity/BaseActivity.java
src/main/java/com/mapzen/open/route/RouteFragment.java

(The fragment lifecycle requires a lot of defensive programming.)

More null checks

---

src/main/java/com/mapzen/open/util/MapzenNotificationCreator.java
src/test/java/com/mapzen/open/util/MapzenNotificationCreatorTest.java

Sets ongoing flag so notifications cannot be dismissed

Make notifications sticky

---

src/main/java/com/mapzen/open/route/RouteFragment.java
src/test/java/com/mapzen/open/route/RouteFragmentTest.java

Prevents from showing on base map after quitting navigation

Hide route marker in onPause instead of onDestroy

---

pom.xml

Fixes IntelliJ editor language level errors e.g. `@Override` for interfaces

Specifies JDK source and compile version to pom.xml
